"""
Local, offline invoice field extraction — zero third-party packages, zero
AI/cloud API calls. Pure Python standard library only.

Two stages:
  1. `extract_pdf_text()` — a from-scratch PDF text-layer reader (parses
     indirect objects, decompresses FlateDecode content streams, and
     decodes the Tj/TJ text-showing operators). Only handles classic,
     unencrypted PDF structure with simple (1-byte-per-character) text
     encoding, which covers most software-generated invoices — but NOT
     encrypted PDFs, scanned/photographed images, or PDFs using CID/
     Identity-H embedded fonts (no ToUnicode CMap resolution is
     implemented). Raises a clear, specific error in those cases rather
     than silently returning garbage.
  2. `extract_fields()` — regex/keyword rules over that text to find
     product name, dates, amounts, brand, warranty info, etc.

Honesty about accuracy: this is fundamentally weaker than an LLM reading
the document, especially for `product_name` (which has no reliable
generic pattern across invoice layouts). Every field records *why* it
was or wasn't found in `warnings`, and `confidence` reflects how much
was actually pinned down vs. guessed — treat `confidence: "low"` results
as needing manual review.
"""

import datetime
import hashlib
import re
import struct
import zlib

# Presence check for "does this document look like an invoice/receipt at
# all" — used by extract_pdf_text() to refuse documents that clearly
# aren't purchase records (a resume, a government form, ...) before any
# field extraction runs. Real invoices/receipts always carry at least one
# of these: a currency symbol, or one of the standard purchase-document
# words. This is intentionally permissive (a broad OR, not a strict AND)
# — the goal is only to reject documents with NONE of these signals, not
# to second-guess documents that do have them.
_INVOICE_SIGNAL_RE = re.compile(
    r"[$£€₹]"
    r"|\binvoice\b|\breceipt\b|\border\s+confirmation\b|\bpurchase\s+order\b"
    r"|\bsubtotal\b|\bsub[- ]total\b|\bamount\s+due\b|\btotal\s+due\b"
    r"|\bgst\b|\bvat\b|\btotal\b|\btax\s+invoice\b",
    re.IGNORECASE,
)

# --------------------------------------------------------------------------
# Errors
# --------------------------------------------------------------------------


class PdfExtractionError(Exception):
    """Base class — callers should catch this and surface `.message`."""

    code = "pdf_extraction_failed"

    def __init__(self, message, code=None):
        super().__init__(message)
        self.message = message
        if code is not None:
            self.code = code


class EncryptedPdfError(PdfExtractionError):
    """Raised when the file IS encrypted but decryption didn't work out —
    e.g. it actually needs a non-empty password to open."""

    code = "encrypted_pdf"


class UnsupportedEncryptionError(PdfExtractionError):
    """Raised when the file's encryption scheme isn't one this from-scratch
    reader implements (only classic RC4, /V 1 and /V 2, is supported —
    no AES, no public-key security handlers)."""

    code = "unsupported_encryption"


class UnreadablePdfError(PdfExtractionError):
    code = "unreadable_pdf"


class ImageNotSupportedError(PdfExtractionError):
    code = "ocr_not_available"


class NotAnInvoiceError(PdfExtractionError):
    """Raised when the document's text was read successfully but contains
    none of the usual invoice/receipt signals at all — e.g. a passport
    application form or a resume. Text extraction succeeding is not the
    same as the document BEING an invoice; without this check, a random
    date found anywhere in an unrelated document (a date of birth, a form
    submission date) could get confidently reported as "purchase_date"
    with a fabricated warranty period built on top of it. Refusing
    outright is safer than guessing on a document with no purchase
    context at all — and matters more than usual here, since some
    documents that fail this check (a passport form, in the case this
    was written for) carry genuinely sensitive personal data that
    shouldn't be echoed into unrelated fields even accidentally."""

    code = "not_an_invoice"


# --------------------------------------------------------------------------
# Stage 0: classic PDF "Standard" security handler (RC4 only — no AES)
# --------------------------------------------------------------------------
#
# Many invoice/order-confirmation PDFs generated by business software are
# "encrypted" purely to restrict editing/printing — they open with no
# password prompt at all, i.e. an empty *user* password. That's exactly
# what this implements: PDF spec Algorithm 3.2 (compute the file's base
# encryption key) and Algorithm 3.1 (derive each object's own RC4 key from
# it), covering security handler /V 1 and /V 2 (both classic RC4; /R 2/3/4).
# AES (/V 4 crypt filters, /V 5 = AES-256) and non-empty passwords are
# explicitly NOT supported — see UnsupportedEncryptionError / EncryptedPdfError.

_PAD = bytes([
    0x28, 0xBF, 0x4E, 0x5E, 0x4E, 0x75, 0x8A, 0x41,
    0x64, 0x00, 0x4E, 0x56, 0xFF, 0xFA, 0x01, 0x08,
    0x2E, 0x2E, 0x00, 0xB6, 0xD0, 0x68, 0x3E, 0x80,
    0x2F, 0x0C, 0xA9, 0xFE, 0x64, 0x53, 0x69, 0x7A,
])

_ENCRYPT_REF_RE = re.compile(rb"/Encrypt\s+(\d+)\s+0\s+R")
_ID_RE = re.compile(rb"/ID\s*\[\s*<([0-9A-Fa-f]+)>")
_ENC_FILTER_RE = re.compile(rb"/Filter\s*/(\w+)")
_ENC_V_RE = re.compile(rb"/V\s+(\d+)")
_ENC_R_RE = re.compile(rb"/R\s+(\d+)")
_ENC_LENGTH_RE = re.compile(rb"/Length\s+(\d+)")
_ENC_P_RE = re.compile(rb"/P\s+(-?\d+)")
_ENC_O_RE = re.compile(rb"/O\s*\(((?:\\.|[^\\()])*)\)")
_LITERAL_ESCAPE_SIMPLE = {
    0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09, 0x62: 0x08, 0x66: 0x0C,
    0x28: 0x28, 0x29: 0x29, 0x5C: 0x5C,
}


def _decode_literal_bytes(raw: bytes) -> bytes:
    """Resolve PDF literal-string escapes, returning raw bytes (not text) —
    used for binary strings like /O and /U, not just display text."""
    out = bytearray()
    i, n = 0, len(raw)
    while i < n:
        c = raw[i]
        if c == 0x5C and i + 1 < n:  # backslash
            nxt = raw[i + 1]
            if nxt in _LITERAL_ESCAPE_SIMPLE:
                out.append(_LITERAL_ESCAPE_SIMPLE[nxt])
                i += 2
                continue
            if 0x30 <= nxt <= 0x39:  # octal escape, up to 3 digits
                j = i + 1
                digits = b""
                while j < n and len(digits) < 3 and 0x30 <= raw[j] <= 0x39:
                    digits += bytes([raw[j]])
                    j += 1
                try:
                    out.append(int(digits, 8) & 0xFF)
                except ValueError:
                    pass
                i = j
                continue
            if nxt in (0x0D, 0x0A):  # escaped line break — not part of the string
                i += 2
                if nxt == 0x0D and i < n and raw[i] == 0x0A:
                    i += 1
                continue
            out.append(nxt)
            i += 2
            continue
        out.append(c)
        i += 1
    return bytes(out)


def _rc4(key: bytes, data: bytes) -> bytes:
    key_len = len(key)
    S = list(range(256))
    j = 0
    for i in range(256):
        j = (j + S[i] + key[i % key_len]) & 0xFF
        S[i], S[j] = S[j], S[i]
    out = bytearray(len(data))
    i = j = 0
    for idx in range(len(data)):
        i = (i + 1) & 0xFF
        j = (j + S[i]) & 0xFF
        S[i], S[j] = S[j], S[i]
        out[idx] = data[idx] ^ S[(S[i] + S[j]) & 0xFF]
    return bytes(out)


def _get_encryption_key(raw: bytes, objects: dict):
    """Return the file's base RC4 key assuming an empty user password, or
    None if the document isn't encrypted at all. Raises
    UnsupportedEncryptionError for AES/non-RC4 handlers."""
    encrypt_ref = _ENCRYPT_REF_RE.search(raw)
    if not encrypt_ref:
        return None
    enc_num = int(encrypt_ref.group(1))
    entry = objects.get(enc_num)
    if entry is None:
        raise UnreadablePdfError("Could not locate the PDF's /Encrypt dictionary.")
    _gen, enc_body = entry

    filt = _ENC_FILTER_RE.search(enc_body)
    if filt and filt.group(1) != b"Standard":
        raise UnsupportedEncryptionError(
            f"This PDF uses a non-standard security handler "
            f"('{filt.group(1).decode(errors='replace')}') this offline "
            "extractor doesn't support."
        )

    v_match = _ENC_V_RE.search(enc_body)
    v = int(v_match.group(1)) if v_match else 0
    if v not in (1, 2):
        raise UnsupportedEncryptionError(
            f"This PDF uses encryption algorithm /V {v} (AES or a public-key "
            "handler) — this offline extractor only implements classic RC4 "
            "encryption (/V 1 and /V 2)."
        )

    r_match = _ENC_R_RE.search(enc_body)
    r = int(r_match.group(1)) if r_match else 2

    length_match = _ENC_LENGTH_RE.search(enc_body)
    key_len = (int(length_match.group(1)) // 8) if length_match else 5

    p_match = _ENC_P_RE.search(enc_body)
    p_value = int(p_match.group(1)) if p_match else -1

    o_match = _ENC_O_RE.search(enc_body)
    if not o_match:
        raise UnreadablePdfError("Could not parse the /O value from the /Encrypt dictionary.")
    o_value = _decode_literal_bytes(o_match.group(1))

    id_match = _ID_RE.search(raw)
    doc_id = bytes.fromhex(id_match.group(1).decode()) if id_match else b""

    # Algorithm 3.2: pad the (assumed empty) user password, hash it together
    # with /O, /P, and the first /ID element.
    md5 = hashlib.md5()
    md5.update(_PAD)
    md5.update(o_value)
    md5.update(struct.pack("<i", p_value))
    md5.update(doc_id)
    key = md5.digest()

    if r >= 3:
        for _ in range(50):
            key = hashlib.md5(key[:key_len]).digest()

    return key[:key_len]


def _object_rc4_key(base_key: bytes, obj_num: int, gen_num: int) -> bytes:
    """Algorithm 3.1: each object is RC4-encrypted with its own key derived
    from the file key plus its object/generation numbers."""
    md5 = hashlib.md5()
    md5.update(base_key)
    md5.update(struct.pack("<I", obj_num)[:3])
    md5.update(struct.pack("<I", gen_num)[:2])
    digest = md5.digest()
    return digest[: min(len(base_key) + 5, 16)]


# --------------------------------------------------------------------------
# Stage 1: PDF structure parsing
# --------------------------------------------------------------------------

_OBJ_RE = re.compile(rb"(\d+)\s+(\d+)\s+obj(.*?)endobj", re.DOTALL)
_LENGTH_RE = re.compile(rb"/Length\s+(\d+)")
_FILTER_RE = re.compile(rb"/Filter\s*\[?\s*/?(\w+)")
_TYPE_PAGE_RE = re.compile(rb"/Type\s*/Page(?![A-Za-z])")
_CONTENTS_SINGLE_RE = re.compile(rb"/Contents\s+(\d+)\s+0\s+R")
_CONTENTS_ARRAY_RE = re.compile(rb"/Contents\s*\[([^\]]*)\]")
_REF_RE = re.compile(rb"(\d+)\s+0\s+R")


def _parse_objects(raw: bytes) -> dict:
    """Map object number -> (generation number, raw object body bytes)."""
    objects = {}
    for num, gen, body in _OBJ_RE.findall(raw):
        objects[int(num)] = (int(gen), body)
    return objects


def _get_stream_bytes(body: bytes, decrypt_key=None, obj_num=None, gen_num=0):
    """Extract and decompress a single object's stream, if it has one.
    If the document is encrypted, `decrypt_key` + the object's own
    number/generation are required to RC4-decrypt the raw bytes *before*
    decompression (encryption wraps the already-filtered stream)."""
    dict_part, sep, rest = body.partition(b"stream")
    if not sep:
        return None
    if rest[:2] == b"\r\n":
        rest = rest[2:]
    elif rest[:1] in (b"\n", b"\r"):
        rest = rest[1:]

    length_match = _LENGTH_RE.search(dict_part)
    if length_match:
        raw_stream = rest[: int(length_match.group(1))]
    else:
        raw_stream = rest.split(b"endstream")[0]

    if decrypt_key is not None and obj_num is not None:
        obj_key = _object_rc4_key(decrypt_key, obj_num, gen_num)
        raw_stream = _rc4(obj_key, raw_stream)

    filter_match = _FILTER_RE.search(dict_part)
    filt = filter_match.group(1) if filter_match else None

    if filt == b"FlateDecode":
        try:
            return zlib.decompress(raw_stream)
        except zlib.error:
            if decrypt_key is not None:
                # A wrong decryption key produces zlib garbage — no point
                # rescanning for 'endstream', the bytes are already wrong.
                return None
            # Length may have been slightly off (off-by-one CR/LF quirks) —
            # fall back to scanning for the literal 'endstream' marker.
            try:
                return zlib.decompress(rest.split(b"endstream")[0])
            except zlib.error:
                return None
    if filt in (None, b"ASCIIHexDecode", b"ASCII85Decode"):
        # Uncompressed or a filter we don't implement — return as-is; the
        # text-run scan below will simply find nothing useful in it rather
        # than crashing.
        return raw_stream
    return None


# --------------------------------------------------------------------------
# Stage 1a: CID font support (/Encoding /Identity-H + /ToUnicode CMap)
# --------------------------------------------------------------------------
#
# Many modern PDF generators (headless-Chrome/wkhtmltopdf-style invoice
# templates, in particular) embed each webfont as a CID font with
# /Encoding /Identity-H: every glyph is shown as a 2-byte code (a raw
# font-internal glyph index, NOT a character code), and the *only* way to
# recover the actual text is via that font's /ToUnicode CMap, which maps
# each 2-byte code back to real Unicode. Fonts using a plain 1-byte
# encoding (WinAnsi/StandardEncoding — what Dell/JB Hi-Fi/Daisy Pool
# Covers all use) are unaffected by any of this and keep using the
# existing single-byte decode path below.

_FONT_OBJ_RE = re.compile(rb"/Type\s*/Font\b")
_IDENTITY_H_RE = re.compile(rb"/Encoding\s*/Identity-H\b")
_TOUNICODE_REF_RE = re.compile(rb"/ToUnicode\s+(\d+)\s+0\s+R")
_PAGE_FONT_DICT_RE = re.compile(rb"/Font\s*<<(.*?)>>", re.DOTALL)
_FONT_RESOURCE_ENTRY_RE = re.compile(rb"/([A-Za-z0-9+\-_.]+)\s+(\d+)\s+0\s+R")

_BFCHAR_BLOCK_RE = re.compile(rb"beginbfchar(.*?)endbfchar", re.DOTALL)
_BFCHAR_PAIR_RE = re.compile(rb"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>")
_BFRANGE_BLOCK_RE = re.compile(rb"beginbfrange(.*?)endbfrange", re.DOTALL)
_BFRANGE_ENTRY_RE = re.compile(
    rb"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*(?:<([0-9A-Fa-f]+)>|\[((?:\s*<[0-9A-Fa-f]+>)+)\s*\])",
    re.DOTALL,
)
_BFRANGE_ARRAY_ITEM_RE = re.compile(rb"<([0-9A-Fa-f]+)>")


def _hex_to_unicode(hex_bytes: bytes) -> str:
    """A ToUnicode destination value is hex-encoded UTF-16BE."""
    hex_str = re.sub(rb"\s+", b"", hex_bytes)
    if len(hex_str) % 2:
        hex_str += b"0"
    try:
        raw = bytes.fromhex(hex_str.decode("ascii"))
    except ValueError:
        return ""
    if len(raw) % 2:
        raw += b"\x00"
    try:
        return raw.decode("utf-16-be", errors="replace")
    except UnicodeDecodeError:
        return ""


def _parse_tounicode_cmap(cmap_bytes: bytes) -> dict:
    """Parse a /ToUnicode CMap stream's beginbfchar/beginbfrange blocks into
    {cid: unicode_string}."""
    mapping = {}
    for block in _BFCHAR_BLOCK_RE.findall(cmap_bytes):
        for src, dst in _BFCHAR_PAIR_RE.findall(block):
            mapping[int(src, 16)] = _hex_to_unicode(dst)
    for block in _BFRANGE_BLOCK_RE.findall(cmap_bytes):
        for m in _BFRANGE_ENTRY_RE.finditer(block):
            start_hex, end_hex, dst_hex, dst_array = m.groups()
            start, end = int(start_hex, 16), int(end_hex, 16)
            if end < start or end - start > 65536:
                continue  # malformed range — never trust it into a huge loop
            if dst_array is not None:
                items = _BFRANGE_ARRAY_ITEM_RE.findall(dst_array)
                for i, item_hex in enumerate(items):
                    if start + i > end:
                        break
                    mapping[start + i] = _hex_to_unicode(item_hex)
            elif dst_hex is not None:
                dst_len = len(dst_hex)
                dst_val = int(dst_hex, 16)
                for i, cid in enumerate(range(start, end + 1)):
                    hex_repr = format(dst_val + i, f"0{dst_len}x").encode("ascii")
                    mapping[cid] = _hex_to_unicode(hex_repr)
    return mapping


def _build_font_unicode_maps(objects: dict, decrypt_key=None) -> dict:
    """Return {font_object_number: {cid: unicode_string}} for every
    Identity-H CID font in the document that has a /ToUnicode CMap. Simple
    (non-CID) fonts are deliberately excluded even if they also carry a
    /ToUnicode entry — they stay on the existing 1-byte decode path."""
    result = {}
    for num, (gen, body) in objects.items():
        if not _FONT_OBJ_RE.search(body) or not _IDENTITY_H_RE.search(body):
            continue
        ref = _TOUNICODE_REF_RE.search(body)
        if not ref:
            continue
        cmap_num = int(ref.group(1))
        cmap_entry = objects.get(cmap_num)
        if cmap_entry is None:
            continue
        cmap_gen, cmap_body = cmap_entry
        cmap_bytes = _get_stream_bytes(cmap_body, decrypt_key=decrypt_key, obj_num=cmap_num, gen_num=cmap_gen)
        if cmap_bytes:
            result[num] = _parse_tounicode_cmap(cmap_bytes)
    return result


def _get_page_font_map(page_body: bytes) -> dict:
    """Parse a page's /Resources /Font <</F1 7 0 R .../>> into
    {resource_name_str: font_object_number}."""
    m = _PAGE_FONT_DICT_RE.search(page_body)
    if not m:
        return {}
    return {name.decode("ascii"): int(num) for name, num in _FONT_RESOURCE_ENTRY_RE.findall(m.group(1))}


def _find_page_content_streams(raw: bytes, objects: dict, decrypt_key=None):
    """Return a list of (content_bytes, page_font_map, font_unicode_maps)
    for every /Type /Page object — the extra two are needed downstream to
    correctly decode any Identity-H CID-encoded text on that page."""
    font_unicode_maps = _build_font_unicode_maps(objects, decrypt_key=decrypt_key)
    streams = []
    for num in sorted(objects):
        gen, body = objects[num]
        if not _TYPE_PAGE_RE.search(body):
            continue

        page_font_map = _get_page_font_map(body)

        content_nums = []
        single = _CONTENTS_SINGLE_RE.search(body)
        if single:
            content_nums.append(int(single.group(1)))
        else:
            array = _CONTENTS_ARRAY_RE.search(body)
            if array:
                content_nums.extend(int(n) for n in _REF_RE.findall(array.group(1)))

        for cnum in content_nums:
            entry = objects.get(cnum)
            if entry is None:
                continue
            cgen, cbody = entry
            data = _get_stream_bytes(cbody, decrypt_key=decrypt_key, obj_num=cnum, gen_num=cgen)
            if data:
                streams.append((data, page_font_map, font_unicode_maps))
    return streams


# --------------------------------------------------------------------------
# Stage 1b: content-stream text-showing operator decoding
# --------------------------------------------------------------------------

_BT_ET_RE = re.compile(rb"BT(.*?)ET", re.DOTALL)
# Adds a font-switch alternative (Tf) ahead of the text-showing operators
# so _decode_content_stream can track which font is active and choose the
# right hex-decoding strategy (CID/Identity-H vs. plain single-byte).
_TEXT_TOKEN_RE = re.compile(
    rb"/([A-Za-z0-9+\-_.]+)\s+[+-]?[\d.]+\s+Tf"  # font switch: /F13 12 Tf
    rb"|\(((?:\\.|[^\\()])*)\)\s*Tj"  # (literal string) Tj
    rb"|<([0-9A-Fa-f\s]*)>\s*Tj"  # <hex string> Tj
    rb"|\[(.*?)\]\s*TJ",  # [ ...array... ] TJ
    re.DOTALL,
)
_ARRAY_ITEM_RE = re.compile(rb"\(((?:\\.|[^\\()])*)\)|<([0-9A-Fa-f\s]*)>")

def _decode_literal(raw: bytes) -> str:
    """Decode a PDF literal string as display text (built on the same
    byte-level escape resolution used for binary /O and /U strings)."""
    return _decode_literal_bytes(raw).decode("latin-1")


def _decode_hex(raw: bytes) -> str:
    """Plain single-byte-per-character hex decode — used for simple
    (non-CID) fonts, i.e. everything except Identity-H CID fonts."""
    hexstr = re.sub(rb"\s+", b"", raw)
    if len(hexstr) % 2:
        hexstr += b"0"
    try:
        data = bytes.fromhex(hexstr.decode("ascii"))
    except ValueError:
        return ""
    return data.decode("cp1252", errors="replace")


def _decode_hex_for_font(raw: bytes, font_obj, font_unicode_maps: dict) -> str:
    """Hex-string decode that's font-aware: if the currently active font is
    a CID/Identity-H font with a known /ToUnicode map, decode 2 bytes per
    glyph and look each one up in that map. Otherwise fall back to the
    plain single-byte decode (_decode_hex) used by simple fonts."""
    cmap = font_unicode_maps.get(font_obj) if font_obj is not None else None
    if not cmap:
        return _decode_hex(raw)
    hexstr = re.sub(rb"\s+", b"", raw)
    if len(hexstr) % 4:
        hexstr += b"0" * (4 - len(hexstr) % 4)
    out = []
    for i in range(0, len(hexstr), 4):
        try:
            cid = int(hexstr[i : i + 4], 16)
        except ValueError:
            continue
        out.append(cmap.get(cid, ""))
    return "".join(out)


def _decode_content_stream(data: bytes, page_font_map=None, font_unicode_maps=None) -> str:
    page_font_map = page_font_map or {}
    font_unicode_maps = font_unicode_maps or {}
    lines = []
    current_font_obj = None  # persists across BT/ET blocks, like real graphics state
    for block_match in _BT_ET_RE.finditer(data):
        block = block_match.group(1)
        parts = []
        for m in _TEXT_TOKEN_RE.finditer(block):
            font_name, literal, hexed, array = m.group(1), m.group(2), m.group(3), m.group(4)
            if font_name is not None:
                current_font_obj = page_font_map.get(font_name.decode("ascii"))
                continue
            if literal is not None:
                parts.append(_decode_literal(literal))
            elif hexed is not None:
                parts.append(_decode_hex_for_font(hexed, current_font_obj, font_unicode_maps))
            elif array is not None:
                for item in _ARRAY_ITEM_RE.finditer(array):
                    if item.group(1) is not None:
                        parts.append(_decode_literal(item.group(1)))
                    elif item.group(2) is not None:
                        parts.append(_decode_hex_for_font(item.group(2), current_font_obj, font_unicode_maps))
        line = "".join(parts).strip()
        if line:
            lines.append(line)
    return "\n".join(lines)


def extract_pdf_text(file_bytes: bytes) -> str:
    """Return the best-effort plain text layer of a PDF, or raise a
    PdfExtractionError subclass explaining why it couldn't.

    Encrypted PDFs are handled by assuming an empty user password (the
    common case for vendor-generated invoices that are merely edit/print
    restricted, not actually password-locked) and decrypting with classic
    RC4 — see _get_encryption_key(). AES and genuinely password-protected
    PDFs raise a clear, specific error rather than pretending to succeed."""
    objects = _parse_objects(file_bytes)
    if not objects:
        raise UnreadablePdfError(
            "Could not parse any objects from this file — it may not be a "
            "valid PDF, or uses a structure (e.g. compressed cross-reference "
            "streams) this offline extractor doesn't support."
        )

    # UnsupportedEncryptionError propagates as-is (AES / non-Standard
    # handler) — nothing we can do about those without a real crypto lib.
    decrypt_key = _get_encryption_key(file_bytes, objects)

    streams = _find_page_content_streams(file_bytes, objects, decrypt_key=decrypt_key)
    if not streams:
        raise UnreadablePdfError(
            "Could not locate any readable page content in this PDF."
        )

    text = "\n".join(
        _decode_content_stream(s, page_font_map=pfm, font_unicode_maps=fum)
        for s, pfm, fum in streams
    ).strip()
    if len(text) < 10:
        if decrypt_key is not None:
            raise EncryptedPdfError(
                "This PDF is encrypted, and decryption was attempted assuming "
                "an empty user password, but produced no readable text — it "
                "likely needs an actual password to open, which this offline "
                "extractor has no way to be given."
            )
        raise UnreadablePdfError(
            "Extracted almost no text from this PDF — it likely uses an "
            "embedded font encoding (e.g. CID/Identity-H) this offline "
            "extractor can't decode, or is a scanned image with no text "
            "layer at all."
        )

    check_invoice_signals(text)
    return text


def check_invoice_signals(text: str) -> None:
    """Raise NotAnInvoiceError if `text` carries none of the usual
    invoice/receipt markers. Public so both the PDF path (above) and the
    OCR path (image_ocr.py, for photographed receipts) apply the exact
    same "does this even look like a purchase document" gate before any
    field extraction runs."""
    if not _INVOICE_SIGNAL_RE.search(text):
        raise NotAnInvoiceError(
            "This document doesn't contain any of the usual invoice/receipt "
            "signals — no currency amount, and none of 'invoice', 'receipt', "
            "'total', 'GST'/'VAT', etc. It doesn't look like a purchase "
            "document, so nothing was extracted from it rather than risk "
            "returning a field (e.g. 'purchase_date') pulled from unrelated "
            "content on the page."
        )


# --------------------------------------------------------------------------
# Stage 2: rule-based field extraction from plain text
# --------------------------------------------------------------------------

_MONTH_NUMS = {
    m: i
    for i, m in enumerate(
        ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"],
        start=1,
    )
}

# Digit-adjacent lookarounds instead of \b: PDF text-run extraction often
# loses the whitespace between two visually-adjacent-but-separately-drawn
# text runs (e.g. a label glued straight onto the next cell's text, as in
# "Order Date:\xa018/09/2018Dell Order No:") — \b fails to match at a
# digit/letter boundary because both are "word" characters to \b, so
# "2018Dell" would silently never match at all. (?<!\d)/(?!\d) only guard
# against the date being a substring of a *longer number*, which is the
# actual failure mode worth preventing.
_DATE_PATTERNS = [
    (re.compile(r"(?<!\d)(\d{1,2})/(\d{1,2})/(\d{4})(?!\d)"), "dmy4"),
    (re.compile(r"(?<!\d)(\d{4})-(\d{2})-(\d{2})(?!\d)"), "iso"),
    # [,\s-]+ (not a single [-\s] char) so "30 November, 2025" — comma
    # *and* space between month and year — matches too, not just the
    # hyphen/space-only "04-Apr-2024" style.
    (re.compile(r"(?<!\d)(\d{1,2})[-\s]([A-Za-z]{3,9})[,\s-]+(\d{4})(?!\d)"), "dmonY"),
    # US-style "Mon Mar 03 2025" (month name *before* the day) — the
    # leading weekday-name word is optional and not captured.
    (
        re.compile(
            r"(?:\b[A-Za-z]{3,9}\s+)?\b([A-Za-z]{3,9})\s+(\d{1,2})\s*,?\s+(\d{4})(?!\d)"
        ),
        "monDY",
    ),
    # Ordinal "5th May 2026" / "21st December 2024". The (?<!\d) guard is
    # load-bearing, not decorative: a run-together "Tax Invoice # 47815th
    # May 2026" (invoice number glued directly onto the date with no
    # separator — a real case seen on a NextGen Living-style invoice)
    # would otherwise let \d{1,2} backtrack into the invoice number and
    # misread "15th" out of "...4781" + "5th", silently returning the
    # wrong day. Refusing to match when the leading digit is
    # digit-adjacent means this glued case is correctly left unparsed
    # (falls through to "no date found") rather than parsed wrong.
    (
        re.compile(
            r"(?<!\d)(\d{1,2})(?:st|nd|rd|th)\s+([A-Za-z]{3,9})\s+(\d{4})(?!\d)",
            re.IGNORECASE,
        ),
        "ordDMY",
    ),
    (re.compile(r"(?<!\d)(\d{1,2})/(\d{1,2})/(\d{2})(?!\d)"), "dmy2"),
]

_DATE_CONTEXT_KEYWORDS = (
    "invoice date", "order date", "purchase date", "date issued", "date:",
    "placed on",
)

# Bounded to 1-2 digits, AND required not to be preceded by another digit
# or hyphen, deliberately: PDF text extraction sometimes runs an adjacent
# table cell's digits (an item/SKU code) straight into the next cell's
# text with no space, e.g. "344-62421" + "1Yr Ltd Hardware Warranty" ->
# "344-624211Yr...". An unbounded \d+ would swallow the SKU's digits too
# and produce nonsense (this previously crashed date math on a
# multi-hundred-thousand-year result); even bounded to 2 digits it would
# still misread "...62421" + "1Yr" as "11Yr". The (?<![\d\-]) lookbehind
# rejects exactly that glued case — if only a glued match exists, we fall
# through to the honest "not found, defaulted to 1 year" path instead of
# trusting a number that's provably contaminated by an adjacent code.
_WARRANTY_DURATION_RE = re.compile(
    r"(?<![\d\-])(\d{1,2})\s*[- ]?\s*(?:yr|year|years)\b", re.IGNORECASE
)

KNOWN_BRANDS = [
    "Daisy Pool Covers", "Apple", "Samsung", "Dell", "HP", "Lenovo", "Asus",
    "Acer", "LG", "Sony", "Panasonic", "Whirlpool", "Bosch", "Garmin",
    "Fitbit", "Google", "Microsoft", "Electrolux", "Fisher & Paykel",
    "Breville", "KitchenAid", "Toshiba", "Hisense", "TCL", "JBL", "Bose",
    "Nikon", "Canon", "GoPro", "Dyson", "Philips", "Sharp", "Haier",
    "Maytronics", "Omron",
]

# Column-header words that can end up looking like a valid "product name"
# or "code" candidate purely because of where they land in the extracted
# text — used by both the code-pair and Description-header search paths
# below to reject header/label text rather than trust it as data.
_TABLE_HEADER_WORDS = {
    "item", "sku", "qty", "qty.", "quantity", "subtotal", "sub-total",
    "sub total", "description", "product description", "unit price",
    "price", "total price", "total", "amount", "value", "disc%",
    "discount", "disc", "gst", "tax", "delivered to", "delivered",
    "billing", "shipping",
}

CATEGORY_KEYWORDS = [
    ("Electronics", ["iphone", "smartphone", "phone", "laptop", "computer", "television",
                      " tv ", "camera", "smartwatch", "tablet", "monitor", "headphone"]),
    ("Appliances", ["refrigerator", "fridge", "washing machine", "dishwasher",
                     "microwave", "oven", "vacuum", "air conditioner"]),
    ("Pool Equipment", ["pool cover", "pool roller", "pool pump", "pool cleaner"]),
    ("Furniture", ["sofa", "wardrobe", "mattress", "recliner"]),
]

_BOILERPLATE_STARTS = (
    "tax invoice", "invoice", "receipt", "thank you", "phone", "abn",
    "www.", "http", "order confirmation", "customer",
)


def _clean_str(value):
    if value is None:
        return None
    value = re.sub(r"\s+", " ", str(value)).strip()
    return value or None


def _parse_date_match(m, kind, warnings):
    try:
        if kind == "dmy4":
            d, mo, y = m.groups()
            return datetime.date(int(y), int(mo), int(d))
        if kind == "dmy2":
            d, mo, y = m.groups()
            yy = int(y)
            year = 2000 + yy if yy < 70 else 1900 + yy
            return datetime.date(year, int(mo), int(d))
        if kind == "dmonY":
            d, mon, y = m.groups()
            month = _MONTH_NUMS.get(mon.lower()[:3])
            if not month:
                return None
            return datetime.date(int(y), month, int(d))
        if kind in ("monDY", "ordDMY"):
            if kind == "monDY":
                mon, d, y = m.groups()
            else:
                d, mon, y = m.groups()
            month = _MONTH_NUMS.get(mon.lower()[:3])
            if not month:
                return None
            return datetime.date(int(y), month, int(d))
        if kind == "iso":
            y, mo, d = m.groups()
            return datetime.date(int(y), int(mo), int(d))
    except ValueError:
        return None
    return None


def _find_purchase_date(text, warnings):
    candidates = []
    for regex, kind in _DATE_PATTERNS:
        for m in regex.finditer(text):
            d = _parse_date_match(m, kind, warnings)
            if d is None:
                continue
            context = text[max(0, m.start() - 40) : m.start()].lower()
            priority = 2 if any(kw in context for kw in _DATE_CONTEXT_KEYWORDS) else (1 if "date" in context else 0)
            candidates.append((priority, m.start(), d))
    if not candidates:
        warnings.append("purchase_date: no date-like value found in the document text.")
        return None
    candidates.sort(key=lambda c: (-c[0], c[1]))
    best = candidates[0]
    if best[0] == 0:
        warnings.append(
            "purchase_date: no 'date' label found near the chosen value; used "
            "the first date-like value in the document — please verify."
        )
    return best[2].isoformat()


def _find_brand(text, warnings):
    for brand in KNOWN_BRANDS:
        if re.search(re.escape(brand), text, re.IGNORECASE):
            return brand
    warnings.append(
        "other_brand_name: not matched against the known-brand list "
        "(local_invoice_extractor.KNOWN_BRANDS) — add it there if this "
        "brand should be recognized."
    )
    return None


def _find_product_code_pair(text):
    """Tabular invoices often print a SKU code on its own line immediately
    followed by a line starting with that same code plus the full
    description, e.g. '525TB' then '525TB Titanium Blue Pool Cover'. This
    catches both the product name AND the code in one reliable shot —
    tried before the weaker single-field heuristics below.

    The code candidate must contain a digit: real SKUs almost always do,
    plain English words practically never do, and requiring one is what
    stops this from misfiring on an unrelated pair of adjacent section
    headers like "Shipping" followed by "Shipping Method" — which has
    exactly the same "line, then a line starting with that line" shape
    this function looks for, but is not product data at all."""
    lines_list = [ln.strip() for ln in text.split("\n")]
    for i in range(len(lines_list) - 1):
        code, nxt = lines_list[i], lines_list[i + 1]
        if not (2 <= len(code) <= 15):
            continue
        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9\-]*$", code):
            continue
        if not re.search(r"\d", code):
            continue
        if nxt.startswith(code) and len(nxt) > len(code) + 2:
            description = nxt[len(code) :].strip(" -:")
            if description and not description[0].isdigit():
                return _clean_str(description), code
    return None, None


def _find_description_then_code(text):
    """The reverse convention from _find_product_code_pair: some invoices
    print the description FIRST and a short SKU-like code on the line
    right after it (e.g. 'Dolphin M 700' then '99996710-AU'), rather than
    the code-then-matching-prefix pattern above.

    This is the weakest/most heuristic of the product-name strategies —
    tried only after the asterisk-line and code-pair checks have both
    failed (see the priority order in extract_fields) — because unlike
    those two, it has no exact-match anchor tying the two lines together;
    it's just "some text, then some code-shaped text on the next line".
    The one thing that reliably distinguishes a real SKU from adjacent
    unrelated data (an email followed by a phone number, a street number
    followed by a suburb, a masked card number, a terminal ID) is that
    real SKUs mix LETTERS and DIGITS — a pure-digit line (a phone number,
    an account number) or a pure-letter line never is one. Checked AFTER
    merging a wrapped trailing segment, since a SKU's first fragment can
    itself be all-digit before the merge (e.g. '99996710-' + 'AU')."""
    lines_list = [ln.strip() for ln in text.split("\n")]
    for i in range(len(lines_list) - 1):
        desc, code = lines_list[i], lines_list[i + 1]
        if not (5 <= len(desc) <= 90):
            continue
        if desc.lower() in _TABLE_HEADER_WORDS:
            continue
        if not re.search(r"[A-Za-z]", desc):
            continue
        # A trailing hyphen is the tell that THIS line is itself a
        # fragment of a wrapped multi-line code, not a real description —
        # a long SKU (e.g. '100-PERCENT-BATTERY-HEALTH-IPHONE-13-PRO')
        # word-wrapped across several short lines produces a run of
        # hyphen-ending fragments, and without this guard the loop pairs
        # two ADJACENT FRAGMENTS OF THE SAME CODE as if one were the
        # description and the next were its code.
        if desc.endswith("-"):
            continue
        # A real item title conventionally starts with a capital letter or
        # digit (or a brand-style lowercase-then-capital lead-in, like
        # "iPhone"). A line starting with an ordinary lowercase word is
        # very likely the tail end of a wrapped sentence/note from the
        # line above it — e.g. "(Note: this / option delays dispatch by
        # one business day)" — not a genuine product name, even though it
        # otherwise looks like harmless descriptive text.
        if not re.match(r"^(?:[A-Z0-9]|[a-z][A-Z])", desc):
            continue
        if not re.match(r"^[A-Za-z0-9][A-Za-z0-9\-]{1,29}$", code):
            continue
        if code.endswith("-") and i + 2 < len(lines_list):
            cont = lines_list[i + 2]
            if re.match(r"^[A-Za-z0-9]{1,8}$", cont):
                code = code + cont
        if not (re.search(r"[A-Za-z]", code) and re.search(r"\d", code)):
            continue
        return _clean_str(desc), code
    return None, None


def _find_asterisk_product_name(text):
    """Highest-confidence product-name signal: retail receipts commonly
    mark taxable/purchased line items with a leading '*'. Tried first,
    ahead of every other strategy, because the marker is explicit rather
    than inferred."""
    lines_list = text.split("\n")
    for i, raw_line in enumerate(lines_list):
        m = re.match(r"^\*\s*([A-Za-z0-9][^\n]{2,80})$", raw_line.strip())
        if not m:
            continue
        name = m.group(1)
        # Retail receipts often wrap the product name onto a short
        # continuation line (e.g. 'GRAPHITE CA' after 'GARMIN - VENU 2S
        # SLATE BEZEL') — merge it in if the next line looks like a
        # continuation rather than a new field.
        if i + 1 < len(lines_list):
            nxt = lines_list[i + 1].strip()
            if nxt and not re.match(r"^[\d\*\-]", nxt) and not nxt.lower().startswith("comments"):
                name = f"{name} {nxt}"
        return _clean_str(name)
    return None


def _find_description_header_product_name(text):
    """Lowest-confidence fallback: a "Description" (or "Product
    Description") table-header line is sometimes followed immediately by
    MORE column headers ("QTY", "UNIT PRICE", "TOTAL PRICE", ...) before
    the actual first product line — a header row with several columns,
    drawn as separate lines. Skip over a bounded run of those before
    trusting a line as real content, rather than blindly grabbing the
    very next line (which used to return "QTY" as a "product name")."""
    header_match = re.search(r"(?im)^\s*(?:product\s+)?description\b\s*$", text)
    if not header_match:
        return None
    remaining = text[header_match.end():].split("\n")
    skipped = 0
    for line in remaining:
        candidate = line.strip()
        if not candidate:
            continue
        if candidate.lower() in _TABLE_HEADER_WORDS:
            skipped += 1
            if skipped > 6:
                return None
            continue
        if candidate.lower().startswith(_BOILERPLATE_STARTS):
            return None
        # A genuinely long, run-together line (several table cells
        # concatenated with no separators — seen when a description
        # cell's text merges with adjacent dimension/quantity data) can't
        # be trusted as a clean product name; honest null beats a
        # garbled 150-character guess.
        if 3 <= len(candidate) <= 120:
            return _clean_str(candidate)
        return None
    return None


_MODEL_NUMBER_LABEL_RE = re.compile(
    r"(?:(?i:item\s*no\.?|model(?:\s*(?:no|number))?|sku))\s*[:.]?\s*([A-Z0-9][A-Z0-9\-]{2,20})"
)
# A table's own column-header row (e.g. "ITEM SKU QTTY GST ...") can have
# its header words glued together with no space by text-run extraction, so
# a label match can accidentally capture the *next* header word instead of
# a real value — reject known header/summary-row words outright rather
# than trust them as a code.
_MODEL_NUMBER_EXCLUDED = {
    "QTY", "QTTY", "GST", "TOTAL", "PRICE", "ITEM", "TAX", "UNIT", "AMOUNT",
    "DESCRIPTION", "DISCOUNT", "SUBTOTAL", "DATE", "NOTES", "TERMS", "SKU",
}
def _find_model_number(text, warnings):
    # NOTE: (?i:...) scopes case-insensitivity to just the label — the
    # whole-pattern (?i) form previously also made the CAPTURED code's
    # [A-Z0-9] class match lowercase, so a header row's next column
    # ("Description", "Quantity", ...) glued onto "Item No." with no space
    # (the same text-run-concatenation issue as the date bug above) would
    # get captured as a bogus "model number".
    #
    # Deliberately no generic "hyphenated all-caps code" fallback beyond
    # this labeled search: an earlier attempt at one (matching any
    # 3+-segment hyphenated token, trusted only when unambiguous) still
    # picked up unrelated hyphenated text with no product connection at
    # all — a freight-surcharge line's internal code and a payment
    # method's "EFTPOS-VISA-MC" label — as if they were the product's
    # model number. A labeled match is a much stronger, safer signal than
    # "looks like a code", so null (with a warning) is the honest answer
    # when no explicit Item No./Model/SKU label is present.
    for m in _MODEL_NUMBER_LABEL_RE.finditer(text):
        candidate = m.group(1)
        if candidate.upper() not in _MODEL_NUMBER_EXCLUDED:
            return candidate

    warnings.append("model_number: no 'Item No./Model/SKU' label found in the document.")
    return None


# A loosely-matched "amount-shaped" token — digits with an integer part of
# any length, then a mandatory decimal separator, then a 2-digit decimal
# part — tolerant of OCR noise that a clean PDF text layer never produces:
# 'O'/'o'/'I'/'l' typed for '0'/'0'/'1'/'1' (classic OCR digit lookalikes),
# a comma used as the decimal separator instead of a period (both appear
# on real receipts depending on locale/printer), and stray whitespace an
# OCR pass sometimes inserts around the separator itself (e.g. photographed
# receipt text read as "8205 , O0" for what a human reads as "$82.05" —
# EasyOCR's known glued-currency-symbol misread). All of that noise is
# resolved by _normalize_amount_token() below; this regex only needs to
# recognize the *shape*.
_AMOUNT_TOKEN = r"[\dOolI][\dOolI,\s]*[.,]\s*[\dOolI]{2}"

_OCR_DIGIT_FIX = str.maketrans({"O": "0", "o": "0", "I": "1", "l": "1"})


def _normalize_amount_token(raw: str):
    """Turn a loosely-matched _AMOUNT_TOKEN capture into a float, or None
    if it doesn't resolve to a plausible amount. Only ever called on text
    a regex has already confirmed is digit/separator/whitespace-shaped
    ending in a 2-digit decimal part, so blanket 'O'/'l' -> '0'/'1'
    substitution can't misfire on ordinary words — it's scoped to numbers
    already recognized as amount-shaped, not applied to text generally.
    The LAST '.' or ',' in the token is taken as the decimal separator
    (whichever punctuation mark that is); every earlier '.'/',' is treated
    as thousands-grouping noise and dropped, rather than trusted to
    reconstruct the original grouping — the exact grouping doesn't matter
    once the decimal point's position is known."""
    token = raw.translate(_OCR_DIGIT_FIX)
    token = re.sub(r"\s+", "", token)
    sep_pos = max(token.rfind("."), token.rfind(","))
    if sep_pos == -1:
        return None
    integer_part = re.sub(r"[.,]", "", token[:sep_pos])
    decimal_part = token[sep_pos + 1 :]
    if not integer_part.isdigit() or len(decimal_part) != 2 or not decimal_part.isdigit():
        return None
    try:
        return float(f"{integer_part}.{decimal_part}")
    except ValueError:
        return None


# Matches a "total" (but not "subtotal"/"sub total") label followed, on the
# SAME line, by a $ amount — this catches the common case where a label
# and its value are drawn as one text run (e.g. "TOTAL PRICE   $  1937.00",
# "Total incl. GST $ 1,649.00"). Deliberately does NOT search across lines:
# PDF content-stream draw order frequently doesn't match visual reading
# order, so hunting further afield risks grabbing an unrelated number (see
# the max-amount fallback's docstring below for the concrete case this
# protects against).
_SAME_LINE_TOTAL_RE = re.compile(
    rf"(?<!sub)(?<!sub )\btotal\b[^\n$]{{0,20}}\$\s*({_AMOUNT_TOKEN})", re.IGNORECASE
)

# Second strategy, for invoices where the label and its value are drawn as
# two SEPARATE lines (own text runs) rather than one combined run — e.g.
# Ozmobiles' summary box:
#   TOTAL :
#   $ 772.50
# Deliberately narrow to avoid the failure mode that motivated the
# same-line-only rule above: only fires when the label line is JUST
# "total" (optionally with a colon) with nothing else on it, AND the
# very next non-blank line (skipping at most one lone "-" sign, for a
# discount row's minus sign on its own line) is ITSELF nothing but a $
# amount. A label like "Invoice Total" does NOT match "total-only", so a
# case where "Invoice Total" is immediately followed by an unrelated
# "Sub-Total" label (as in a Daisy Pool Covers-style invoice, where the
# real total actually appears earlier in the text, not after either
# label) safely falls through to the fallback below unchanged.
_LABEL_ONLY_TOTAL_RE = re.compile(r"^\s*total\s*:?\s*$", re.IGNORECASE)
_LABEL_ONLY_SUBTOTAL_RE = re.compile(r"^\s*sub\s*[- ]?\s*total\b", re.IGNORECASE)
_PURE_AMOUNT_LINE_RE = re.compile(rf"^\s*-?\s*\$\s*({_AMOUNT_TOKEN})\s*$")
_SOLITARY_MINUS_RE = re.compile(r"^\s*-\s*$")


def _find_next_line_total(text):
    lines = text.split("\n")
    found = None
    for i, line in enumerate(lines):
        if _LABEL_ONLY_SUBTOTAL_RE.match(line) or not _LABEL_ONLY_TOTAL_RE.match(line):
            continue
        j = i + 1
        if j < len(lines) and _SOLITARY_MINUS_RE.match(lines[j]):
            j += 1
        if j < len(lines):
            m = _PURE_AMOUNT_LINE_RE.match(lines[j])
            if m:
                amount = _normalize_amount_token(m.group(1))
                if amount is not None:
                    found = amount
    # Last match wins: a discount/tax breakdown's own "total"-ish rows (if
    # any) appear before the final grand total in reading order.
    return found


def _find_purchase_amount(text, warnings):
    same_line = _SAME_LINE_TOTAL_RE.findall(text)
    if same_line:
        amount = _normalize_amount_token(same_line[-1])
        if amount is not None:
            warnings.append(
                f"purchase_amount: taken from the amount immediately following "
                f"a 'total' label on the same line ({amount})."
            )
            return amount

    next_line_total = _find_next_line_total(text)
    if next_line_total is not None:
        warnings.append(
            f"purchase_amount: taken from the amount on the line immediately "
            f"following a standalone 'total' label ({next_line_total})."
        )
        return next_line_total

    # Fallback: collect every $-prefixed amount and take the largest. This
    # is a heuristic, not a real total lookup — it can be wrong when a
    # discount makes the final total *smaller* than the subtotal it's
    # discounted from. It's kept as the fallback because it's empirically
    # correct on several other real invoice layouts where the true total
    # legitimately is the largest number printed, and no explicit total
    # label was found paired with its value.
    amounts = []
    for m in re.finditer(rf"\$\s*({_AMOUNT_TOKEN})", text):
        amount = _normalize_amount_token(m.group(1))
        if amount is not None:
            amounts.append(amount)
    if not amounts:
        warnings.append("purchase_amount: no $-prefixed amount found in the document.")
        return None
    best = max(amounts)
    warnings.append(
        f"purchase_amount: taken as the largest $ amount printed on the "
        f"document ({best}) as a proxy for the grand total — verify against "
        f"the actual invoice total."
    )
    return best


def _find_currency(text):
    # Plain substring checks, deliberately not \b-bounded: acronyms like
    # "ABN" or "AUD" can end up glued directly onto adjacent digits with no
    # separating space after text-run extraction (e.g. "...5000ABN 46..."),
    # which \bABN\b would silently fail to match at all.
    if "AUD" in text or "A$" in text or "AU$" in text:
        return "AUD"
    if "ABN" in text:
        # Australian Business Number — printed on every Australian tax
        # invoice; a strong signal even when "AUD"/"A$" aren't spelled out.
        return "AUD"
    if "GBP" in text or "£" in text:
        return "GBP"
    if "EUR" in text or "€" in text:
        return "EUR"
    if "INR" in text or "₹" in text:
        return "INR"
    if "$" in text:
        return "USD"
    return None


def _find_category(text):
    lower = text.lower()
    for category, keywords in CATEGORY_KEYWORDS:
        if any(kw in lower for kw in keywords):
            return category
    return None


def add_years(d: datetime.date, years: int) -> datetime.date:
    try:
        return d.replace(year=d.year + years)
    except ValueError:
        return d.replace(month=2, day=28, year=d.year + years)


def _build_notes(product_name, brand, purchase_date, category, warranty_mentioned):
    """A short, human-readable description of the purchase — combines what
    was found into one or two plain sentences, rather than exposing raw
    warning fragments to the caller. purchase_amount is deliberately NOT
    included here — it's its own response field (see RESPONSE_FIELDS)."""
    if product_name and brand and brand.lower() not in product_name.lower():
        sentence = f"{brand} {product_name}"
    elif product_name:
        sentence = product_name
    elif brand:
        article = "An" if brand[0].upper() in "AEIOU" else "A"
        sentence = f"{article} {brand} product"
    elif category:
        article = "An" if category[0].upper() in "AEIOU" else "A"
        sentence = f"{article} {category.lower()} item"
    else:
        sentence = "This item"

    parts = [sentence]
    if purchase_date:
        parts.append(f"purchased on {purchase_date}.")
    else:
        parts[-1] = parts[-1].rstrip(".") + "."

    description = " ".join(parts)
    if warranty_mentioned:
        description += " Warranty tracked as 1 year from the purchase date."
    return description.strip()


def extract_fields(text: str) -> dict:
    """Rule-based extraction over already-extracted plain text. Never raises.

    Warranty dates are always computed as purchase_date -> purchase_date +
    1 year whenever a purchase date was found — this is a fixed business
    rule (not conditional on the document mentioning a warranty), matching
    the app's default warranty tracking period."""
    warnings = []

    # Priority order, highest confidence first: an explicit asterisk
    # marker beats an exact code<->prefix match, which beats the looser
    # description-then-code heuristic, which beats the weakest fallback
    # (skip past table headers under a "Description" column). Each is
    # tried only if every higher-priority strategy came up empty.
    product_name = _find_asterisk_product_name(text)
    model_number = None
    if product_name is None:
        product_name, model_number = _find_product_code_pair(text)
    if product_name is None:
        product_name, model_number = _find_description_then_code(text)
    if product_name is None:
        product_name = _find_description_header_product_name(text)
    if product_name is None:
        warnings.append(
            "product_name: no reliable pattern matched (no asterisk-prefixed "
            "line item, no code/description line pair, no usable "
            "'Description' table header found) — needs manual entry."
        )
    if model_number is None:
        model_number = _find_model_number(text, warnings)
    brand = _find_brand(text, warnings)
    purchase_date = _find_purchase_date(text, warnings)
    purchase_amount = _find_purchase_amount(text, warnings)
    currency = _find_currency(text)
    category = _find_category(text)
    warranty_mentioned = bool(re.search(r"warrant|guarantee", text, re.IGNORECASE))

    warranty_start_date = None
    warranty_end_date = None
    if purchase_date is not None:
        start = datetime.date.fromisoformat(purchase_date)
        try:
            warranty_start_date = purchase_date
            warranty_end_date = add_years(start, 1).isoformat()
        except (ValueError, OverflowError):
            # Should be unreachable (purchase_date is already a validated
            # calendar date), but a date-math edge case must never crash
            # the request — fail safe to null rather than a wrong date.
            warnings.append(
                "warranty_end_date: could not compute purchase_date + 1 year; left null."
            )
    else:
        warnings.append(
            "warranty_start_date/warranty_end_date: no purchase_date found to "
            "anchor the 1-year warranty period, so both were left null."
        )

    notes = _build_notes(
        product_name, brand, purchase_date, category, warranty_mentioned
    )

    data = {
        "product_name": product_name,
        "model_number": model_number,
        "other_brand_name": brand,
        "other_category": category,
        "other_categorytype": None,
        "purchase_date": purchase_date,
        "purchase_amount": purchase_amount,
        "currency": currency,
        "warranty_start_date": warranty_start_date,
        "warranty_end_date": warranty_end_date,
        "notes": notes,
        "parts": [],
    }

    core_fields = ["product_name", "purchase_date", "other_brand_name", "purchase_amount"]
    found_count = sum(1 for f in core_fields if data.get(f) is not None)
    weak_signal = any(
        w.startswith(f"{f}:") and ("no " in w or "not matched" in w or "could not" in w)
        for f in core_fields
        for w in warnings
    )
    if found_count == len(core_fields) and not weak_signal:
        confidence = "high"
    elif found_count >= 2:
        confidence = "medium"
    else:
        confidence = "low"
    data["confidence"] = confidence

    fields_not_found = sorted(f for f in core_fields + ["model_number"] if data.get(f) is None)
    data["fields_not_found"] = fields_not_found
    data["warnings"] = warnings

    return data


# --------------------------------------------------------------------------
# API response shaping — shared by both extraction/views.py (Django) and
# standalone_api.py so they return byte-identical JSON for the same file.
# --------------------------------------------------------------------------

RESPONSE_FIELDS = (
    "product_name",
    "model_number",
    "other_brand_name",
    "purchase_date",
    "purchase_amount",
    "warranty_start_date",
    "warranty_end_date",
    "notes",
)


def build_success_response(fields: dict) -> dict:
    """Flat response shape: {status: 1, <the 8 requested fields>}. Extra
    diagnostic data (confidence/warnings/etc.) from extract_fields() is
    intentionally NOT included here — this is the exact, minimal field set
    requested for the API contract."""
    response = {"status": 1}
    for key in RESPONSE_FIELDS:
        response[key] = fields.get(key)
    return response


def build_error_response(message: str) -> dict:
    """Flat error shape: {status: 0, message: "..."}."""
    return {"status": 0, "message": message}
